CONFIG_RT_TIMER_THREAD_STACK_SIZE=2048
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_BSP_USING_FULL_ASSERT=y

# CherryUSB Host support (for RNDIS Host)
# CONFIG_BSP_USING_USBD is not set
CONFIG_PKG_USING_CHERRYUSB=y
CONFIG_PKG_CHERRYUSB_HOST=y
CONFIG_PKG_CHERRYUSB_HOST_MUSB_SIFLI=y
CONFIG_PKG_CHERRYUSB_HOST_CDC_RNDIS=y
CONFIG_CONFIG_USBHOST_REQUEST_BUFFER_LEN=2048
CONFIG_CONFIG_USBHOST_CONTROL_TRANSFER_TIMEOUT=5000
CONFIG_PKG_USING_CHERRYUSB_LATEST_VERSION=y

# lwIP configuration (required by RNDIS)
CONFIG_RT_USING_LWIP=y
CONFIG_RT_USING_LWIP212=y
CONFIG_RT_LWIP_IP_FORWARD=y
CONFIG_LWIP_USING_NAT=y
CONFIG_RT_USING_NETDEV=y
CONFIG_NETDEV_USING_IFCONFIG=y
CONFIG_RT_LWIP_TCPTHREAD_STACKSIZE=4096
CONFIG_LWIP_NO_RX_THREAD=y
CONFIG_LWIP_NO_TX_THREAD=y

# Bluetooth Classic PAN/NAP support
CONFIG_RT_USING_BLUETOOTH=y
CONFIG_BLUETOOTH=y
CONFIG_BSP_BLE_SIBLES=y
CONFIG_BT_FINSH=y
CONFIG_BT_PROFILE_CUSTOMIZE=y
CONFIG_CFG_PAN=y
CONFIG_PKG_USING_FLASHDB=y
CONFIG_LWIP_USING_DHCPD=y
CONFIG_DHCPD_SERVER_IP="192.168.43.1"
CONFIG_LWIP_USING_CUSTOMER_DNS_SERVER=y
CONFIG_DHCP_DNS_SERVER_IP="8.8.8.8"
CONFIG_BT_PAN_DUAL_ROLE=y

CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_USING_ISR_LOG=y
