from building import *

cwd = GetCurrentDir()
src = []

CPPPATH = [cwd]
if GetDepend('LVSF_SJPG_OUTPUT_YUV420'):
    lib = [GroupLibName('gui_widgets_yuv420')]
else:
    lib = [GroupLibName('gui_widgets_rgb')]
libpath = [cwd]

group = DefineGroup(
    'gui_widgets',
    src,
    depend=['PKG_USING_LITTLEVGL2RTT'],
    LIBS=lib,
    LIBPATH=libpath,
    CPPPATH=CPPPATH
)

Return('group')
