Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

cwd = GetCurrentDir()
src = []
list = os.listdir(cwd)

CPPPATH = [cwd]
CPPPATH += [os.path.join(cwd, 'include')]

if GetDepend('BF0_ACPU') and GetDepend('ANYKA_RUN_IN_ACPU'):
    CPPPATH += [cwd + '/anyka',]
    objs = group = DefineGroup('anyka', src, depend = ['ANYKA_RUN_IN_ACPU'], CPPPATH = CPPPATH)
    objs = objs + SConscript(os.path.join('anyka', 'SConscript'))
    Return('objs')

if GetDepend('BF0_ACPU') and GetDepend('WEBRTC_RUN_IN_ACPU'):
    CPPPATH += [cwd + '/webrtc',]
    objs = group = DefineGroup('webrtc', src, depend = ['WEBRTC_RUN_IN_ACPU'], CPPPATH = CPPPATH)
    objs = objs + SConscript(os.path.join('webrtc', 'SConscript'))
    Return('objs')

if GetDepend('BF0_HCPU'):
    CPPPATH += [cwd, str(Dir('#'))]
    CPPPATH += [cwd + '/../btdm_internal/plf',]
    CPPPATH += [cwd + '/../../external/libhelix-mp3/pub',]
    CPPPATH += [cwd + '/../app_fwk',]
    CPPPATH += [cwd + '/anyka',]
    CPPPATH += [cwd + '/webrtc',]
    CPPPATH += [cwd + '/vbe_drc',]


objs = group = DefineGroup('audio', src,depend = ['AUDIO'],CPPPATH = CPPPATH)

if GetDepend('AUDIO'):
    if GetDepend('BSP_USING_PC_SIMULATOR'):
        objs = objs + SConscript(os.path.join('pc', 'SConscript'))    
        objs = objs + SConscript(os.path.join('audio_port', 'SConscript'))    
    else:
        for d in list:
            path = os.path.join(cwd, d)
            if os.path.isfile(os.path.join(path, 'SConscript')):
                objs = objs + SConscript(os.path.join(d, 'SConscript'))    

Return('objs')
