# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2025-2026 SiFli Technologies(Nanjing) Co., Ltd
# SPDX-License-Identifier: Apache-2.0
#
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import json
import os

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
import datetime

current_year = datetime.datetime.now().year
project = 'SiFli SDK编程指南'
copyright = '2019 - {} 思澈科技（南京）有限公司'.format(current_year)
author = 'SiFli'
language = 'zh_CN'
version = os.environ.get('SIFLI_DOC_VERSION', 'latest')

if "SF32LB55X" in tags:
    chip = 'sf32lb55x'
elif "SF32LB56X" in tags:
    chip = 'sf32lb56x'
elif "SF32LB57X" in tags:
    chip = 'sf32lb57x'
elif "SF32LB58X" in tags:
    chip = 'sf32lb58x'
elif "SF32LB52X" in tags:
    chip = 'sf32lb52x'
else:
    chip = 'sf32lb52x'

# Algolia DocSearch configuration
docsearch_app_id = os.environ.get('ALGOLIA_DOCSEARCH_APP_ID', '')
docsearch_api_key = os.environ.get('ALGOLIA_DOCSEARCH_SEARCH_API_KEY', '')
docsearch_chips = (
    'sf32lb52x',
    'sf32lb55x',
    'sf32lb56x',
    'sf32lb57x',
    'sf32lb58x',
)
docsearch_index_names = [f"sdk_{version}_{docsearch_chip}" for docsearch_chip in docsearch_chips]

docsearch_agent_ids_json = os.environ.get('ALGOLIA_DOCSEARCH_AGENT_IDS', '').strip()
if docsearch_agent_ids_json:
    try:
        docsearch_agent_ids = json.loads(docsearch_agent_ids_json)
    except json.JSONDecodeError as error:
        raise RuntimeError('ALGOLIA_DOCSEARCH_AGENT_IDS must be a JSON object') from error
else:
    docsearch_agent_ids = {}

if not isinstance(docsearch_agent_ids, dict):
    raise RuntimeError('ALGOLIA_DOCSEARCH_AGENT_IDS must be a JSON object')

docsearch_agent_id = docsearch_agent_ids.get(chip, '')

# DocSearch is initialized from ``static/js/algolia-agent-chat.js`` with the
# v5 JavaScript bundle.  Every page selects the Agent for its current chip,
# while the Agent can search every chip index for the current SDK version.

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ["breathe", 
              "myst_parser", 
              "sphinx_rtd_theme",
              # "sphinx_book_theme",
              "sphinx_multiversion",
              "sphinxcontrib.mermaid",
              "sphinx_copybutton",
              "sphinx.ext.intersphinx",
              #"sphinx_ext_substitution",
              "sphinx_design",
              "sphinx_selective_exclude.eager_only",
              "sphinx_selective_exclude.search_auto_exclude",
              ]

# ``_templates`` is generated by ``generate_docs.py``. Keep the DocSearch
# override separately so it is version-controlled and takes precedence over
# Shibuya's built-in keyword-search form.
templates_path = ['docsearch_templates', '_templates']
exclude_patterns = []

numfig = False


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# html_theme = 'sphinx_rtd_theme'
# html_theme = 'sphinx_book_theme'
html_theme = 'shibuya'
html_static_path = ['../_static', 'static']

html_context = {
    "versions": [
        ("latest", "latest"),
        # 只保留latest版本，其他版本通过JavaScript动态加载
    ],
    "chips": [
        ("SF32LB52x", "sf32lb52x"),
        ("SF32LB56x", "sf32lb56x"),
        ("SF32LB57x", "sf32lb57x"),
        ("SF32LB58x", "sf32lb58x"),
        ("SF32LB55x", "sf32lb55x"),
    ],
    "current_version": version,
    "current_chip": chip,
    "languages": [
        ("English", "", "en"),
        ("中文", "", "zh_CN"),
    ],
    "portal_url": "https://www.sifli.com",
    "wiki_url": "https://wiki.sifli.com",
}

html_logo = '../_static/logo_white.png'
html_favicon = '../_static/logo_favicon.png'

html_show_sourcelink = False
#html_show_copyright = False

html_theme_options = {
    # 'collapse_navigation' : False,
    # 'style_nav_header_background': 'white',
    # 'logo_only': False,
    "accent_color": "blue",
    "github_url": "https://github.com/OpenSiFli/SiFli-SDK",
}

html_css_files = [
    'css/custom.css',
    'css/feedback.css',
    'css/lightbox.css',
]

html_js_files = [
    'js/baidu.js',
    'js/feedback.js',
    'js/lightbox.js',
]


def setup(app):
    """Configure the v5 DocSearch modal and optional Agent Studio Sidepanel."""
    docsearch_config = {
        "appId": docsearch_app_id,
        "apiKey": docsearch_api_key,
        # This is an Agent Studio v5 request allowlist. It contains every
        # supported chip for the current SDK version so explicit cross-chip
        # questions remain searchable.
        "indices": docsearch_index_names,
        "searchParameters": {
            docsearch_index_name: {} for docsearch_index_name in docsearch_index_names
        },
        "agentId": docsearch_agent_id,
        "variant": "floating",
        "side": "right",
        # Agent Studio has no suggested-question index configured for this site.
        # Enabling it makes both AI entry points request a missing index.
        "suggestedQuestions": False,
        "translations": {
            "header": {
                "title": "AI 问答",
            },
            "newConversationScreen": {
                "titleText": "有什么可以帮你？",
                "introductionText": "我会基于当前芯片和版本的 SDK 文档回答问题。",
            },
            "promptForm": {
                "promptPlaceholderText": "请输入关于当前文档的问题...",
            },
        },
        "buttonTranslations": {
            "buttonAriaLabel": "Open Ask AI Sidepanel",
        },
    }
    docsearch_config_json = json.dumps(docsearch_config, ensure_ascii=False).replace(
        "</", "<\\/"
    )
    app.add_js_file(
        None,
        body=f"window.algoliaAgentChatConfig = {docsearch_config_json};",
        priority=790,
    )
    app.add_js_file("js/algolia-agent-chat.js", priority=800, loading_method="defer")

# -- Options for Breathe ----------------------------------------------------

breathe_projects = {"coresdk": os.path.join(os.path.dirname(__file__), r"../../doxygen/xml")}
breathe_default_project = "coresdk"
breathe_domain_by_extension = {"h" : "c"}
breathe_implementation_filename_extensions = ['.c', '.cc', '.cpp']

# -- Options for myst_parser ----------------------------------------------------

myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "attrs_block",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

myst_fence_as_directive = ["mermaid"]

# temp solution to include files according to chip series, esp-docs has more elegant solution. It extends `toctree` directive by `toctree_filter.py`
# `only`和`toctree`指示符不能嵌套使用，当把toctree嵌在only里时，虽然页面上的目录树可以正常显示，但侧边导航栏的显示不正确，而且即使没有被toctree引用的文件也会被转成html
if "SF32LB55X" in tags:
    # HAL
    exclude_patterns = ["**/audcodec.md", "**/audprc.md", "**/atim.md", "**/facc.md", "**/fft.md", "**/hash.md", "**/mpi.md"]
    # Drivers
    exclude_patterns = ["**/spi_flash_52x.md"]
    # App note
    exclude_patterns += ["**/quick_start_52x_56x.md"]
    # Middlware
    exclude_patterns += ["**/bt_service.md"]
    # Example 
    exclude_patterns += ["**/hash/**", "example/bt/**"]
    # app_development
    exclude_patterns += ["**/startup_flow_sf32lb52x.md"]


if "SF32LB58X" in tags:
    # HAL
    exclude_patterns = ["**/hash.md", "**/psram.md", "**/qspi.md"]
    # Drivers
    exclude_patterns = ["**/spi_flash_52x.md"]
    # App note
    exclude_patterns += ["**/quick_start_55x.md", "**/memory_usage.md", "**/dualcore.md"]
    # Middlware
    exclude_patterns += []
    # Example 
    exclude_patterns += ["**/hash/**"]
    # app_development
    exclude_patterns += ["**/startup_flow_sf32lb52x.md"]


if "SF32LB56X" in tags:
    # HAL
    exclude_patterns = ["**/dsi.md", "**/psram.md", "**/qspi.md"]
    # Drivers
    exclude_patterns = ["**/spi_flash_52x.md"]
    # App note
    exclude_patterns += ["**/quick_start_55x.md", "**/memory_usage.md", "**/dualcore.md"]
    # Middlware
    exclude_patterns += []
    # Example 
    exclude_patterns += []    
    # app_development
    exclude_patterns += ["**/startup_flow_sf32lb52x.md"]


if "SF32LB57X" in tags:
    # HAL
    exclude_patterns = ["**/busmon.md", "**/dsi.md", "**/facc.md", "**/fft.md", "**/nnacc.md", "**/psram.md", "**/qspi.md"]
    # Drivers
    exclude_patterns = ["**/spi_flash.md"]
    # App note
    exclude_patterns += ["**/quick_start_55x.md", "**/memory_usage.md", "**/dualcore.md"]
    # Middlware
    exclude_patterns += []
    # Example
    exclude_patterns += ["example/multicore/**"]


if "SF32LB52X" in tags:
    # HAL
    exclude_patterns = ["**/busmon.md", "**/dsi.md", "**/facc.md", "**/fft.md", "**/nnacc.md", "**/psram.md", "**/qspi.md"]
    # Drivers
    exclude_patterns = ["**/spi_flash.md"]
    # App note
    exclude_patterns += ["**/quick_start_55x.md", "**/memory_usage.md", "**/dualcore.md"]
    # Middlware
    exclude_patterns += []
    # Example 
    exclude_patterns += ["example/multicore/**"]


exclude_patterns += ["example/52x_mode_test/*", "example/gpadc/*", "example/micropython/*",
                     "example/hal_example/*", "**/get-started-keil.md"]
