#ifndef __REG_EM_BLE_RX_ISO_BUFFER_H_
#define __REG_EM_BLE_RX_ISO_BUFFER_H_

#define REG_EM_BLE_RX_ISO_BUFFER_SIZE 262

#define REG_EM_BLE_RX_ISO_BUFFER_BASE_ADDR 0x40110000


#endif // __REG_EM_BLE_RX_ISO_BUFFER_H_

